language: julia
os:
- linux
julia:
- 0.6
notifications:
  email: false
after_success:
  - julia -e 'Pkg.add("Coverage");
  - julia -e 'cd(Pkg.dir("BulletCollision")); using Coverage; Coveralls.submit(Coveralls.process_folder())'